### ISSUE TITLE
Importing leads to an error

### ISSUE THREAD

**Issue by TheStarGabro** [SIsilicon/Goddard-ImportExport-Project#5]
Errors always happen whether it's importing or exporting (though I cannot be sure of the latter since I can't import to begin with)

This is when using the old 1a3a90f branch
![image](https://user-images.githubusercontent.com/108905104/179437792-8d911471-0c45-46ef-a504-b414388aeb9f.png)

And this is when using the most recent master branch
![image](https://user-images.githubusercontent.com/108905104/179438051-67ae61d5-b7ba-413d-ac32-076760627ab2.png)

**Comment by DMonitor** [comment]
Import the model from [the decompilation project](https://github.com/n64decomp/sm64)
This error occurs when you attempt to import the model from PC port instead of the decomp.

**Comment by cowboy-bebo** [comment]
I am having the same issue with the import function using blender 2.91 with the latest master branch.
![error-291](https://user-images.githubusercontent.com/109552271/212554291-a3d4395a-6f50-49e3-862b-7c804ccf9c9c.png)

I've also tried using both blender 3.0 and 3.1, but the same error occurs. I am using N64 decomp for this, so I don't know what's going on.

**Comment by SuperMarioTechGuy** [comment]
same anyone has a solution?

**Comment by SuperMarioTechGuy** [comment]
also I now get this Traceback (most recent call last):
  File "C:\Users\Tutorialtechguy\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\goddard_addon\__init__.py", line 64, in execute
    return export_goddard.exceute(self, context)
  File "C:\Users\Tutorialtechguy\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\goddard_addon\export_goddard.py", line 310, in exceute
    master_dynlist = load_dynlist(dynlist_files["master"])
  File "C:\Users\Tutorialtechguy\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\goddard_addon\export_goddard.py", line 39, in load_dynlist
    with open(os.path.join(sm64_source_dir, filepath)) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Tutorialtechguy\\Downloads\\Goddard-ImportExport-Project-1a3a90f2368e2edd3272fbaac31bbc3e604ee3d9\\Goddard-ImportExport-Project-1a3a90f2368e2edd3272fbaac31bbc3e604ee3d9\\..\\..\\..\\..\\..\\msys64\\home\\Tutorialtechguy\\sm64\\src/goddard/dynlists/dynlist_mario_master.c'

location: <unknown location>:-1

anyone fixed it?
